language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "kK0iQoXTkR9iz7z9T8/Wj4VhBbdmJt27TcLUtBLbS0omhmld/PsJKzIcxtfs/Uks3c0DMO/OeEASx33n7P9VsvbCvd5KPcvmemuIrnl+H2ZhqpTrDCKAHbXUaz+RcG5RWDEa+NxCFu93Df4z4A2dkdoGIXi9PukUB/HK25fCI4qwX4EZ1IaGWa1/CjiuxWCW19f0H4dazoJFEnZVxR+dOLysKNZK94jX84OUzsMD0qKzINQ7UywZN/5t68tfKRvIR4Uz7REtCzK9tWrskzmRKSgTsUxcrVvjZkT8Ozc/5UbgXf4tT5r2Bsl9y3+sQnG7Q2UNSpw8BaAgw8xmmU0g40iXWgbXKjX5vmeFhvqpAs6GC870X3CFzP/M+GKaEmmLRQs0JLTBgMrw7ki4Q9RuRRx2m6eIjjAz/FJHaRYE3WA4VN8qTJOXqPvK7gVIAi6jMsljuUL9ptheGarKo1HMeq1OHoXUAXWgDcai50Oaotfe9uWd0L5lKYhWSBCmZQWOVL7Rc1ZNR44pqQr0j/8qwtBmUGwq42uilrDTA7/WzJysL0SWoEVzAZJ2V9KUIcS65lctV/syMYU2NgcwVG7e3IaeirpUVXATho+uGp8eL1GqcjJD5Pa6ThzE45w1a0qC/epna+l3929awOeJDTJxjPWRFqpH0KrxDMKOGSPf4k4="
